/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.taskchecker;

import java.awt.PopupMenu;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;

/**
 *
 * @author Home
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        initComponents();
        
        setLocationRelativeTo(null);

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        task1 = new javax.swing.JLabel();
        task2 = new javax.swing.JLabel();
        task3 = new javax.swing.JLabel();
        task4 = new javax.swing.JLabel();
        task5 = new javax.swing.JLabel();
        task6 = new javax.swing.JLabel();
        task7 = new javax.swing.JLabel();
        task8 = new javax.swing.JLabel();
        task9 = new javax.swing.JLabel();
        task10 = new javax.swing.JLabel();
        maxTaskMessage = new javax.swing.JLabel();
        deleteTaskButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        deleteAllTasksButton = new javax.swing.JButton();
        backGrLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        title.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        title.setText("Today Tasks:");
        jPanel1.add(title);
        title.setBounds(200, 20, 100, 20);

        jTextField1.setBackground(new java.awt.Color(255, 255, 235));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(95, 56, 310, 22);

        confirmButton.setBackground(new java.awt.Color(204, 102, 0));
        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton);
        confirmButton.setBounds(200, 98, 90, 22);
        jPanel1.add(task1);
        task1.setBounds(100, 140, 310, 20);
        task1.setVisible(false);
        jPanel1.add(task2);
        task2.setBounds(100, 162, 310, 20);
        task2.setVisible(false);
        jPanel1.add(task3);
        task3.setBounds(100, 182, 310, 20);
        task3.setVisible(false);
        jPanel1.add(task4);
        task4.setBounds(100, 202, 310, 20);
        task4.setVisible(false);
        jPanel1.add(task5);
        task5.setBounds(100, 222, 310, 20);
        task5.setVisible(false);
        jPanel1.add(task6);
        task6.setBounds(100, 243, 310, 20);
        task6.setVisible(false);
        jPanel1.add(task7);
        task7.setBounds(100, 263, 310, 20);
        task7.setVisible(false);
        jPanel1.add(task8);
        task8.setBounds(100, 284, 310, 20);
        task8.setVisible(false);
        jPanel1.add(task9);
        task9.setBounds(100, 305, 310, 20);
        task9.setVisible(false);
        jPanel1.add(task10);
        task10.setBounds(100, 326, 310, 20);
        task10.setVisible(false);

        maxTaskMessage.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        maxTaskMessage.setForeground(new java.awt.Color(204, 0, 0));
        maxTaskMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxTaskMessage.setText("You reached your maximum amount of task");
        maxTaskMessage.setToolTipText("");
        maxTaskMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(maxTaskMessage);
        maxTaskMessage.setBounds(100, 368, 310, 20);
        maxTaskMessage.setVisible(false);

        deleteTaskButton.setBackground(new java.awt.Color(204, 102, 0));
        deleteTaskButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteTaskButton.setText("Delete Task");
        deleteTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteTaskButton);
        deleteTaskButton.setBounds(190, 429, 120, 22);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 235));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "task1", "task2", "task3", "task4", "task5", "task6", "task7", "task8", "task9", "task10" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(208, 470, 90, 22);

        deleteAllTasksButton.setBackground(new java.awt.Color(204, 102, 0));
        deleteAllTasksButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteAllTasksButton.setText("Delete All Tasks");
        deleteAllTasksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllTasksButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteAllTasksButton);
        deleteAllTasksButton.setBounds(179, 512, 140, 22);

        backGrLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\yosoy\\OneDrive\\Documentos\\NetBeansProjects\\taskChecker\\src\\main\\java\\com\\mycompany\\taskchecker\\images\\notebackgr.jpg")); // NOI18N
        jPanel1.add(backGrLbl);
        backGrLbl.setBounds(0, 0, 430, 560);
        backGrLbl.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // This button sets the text from the text field done by the user into a task in numerical order
        
        if (!task1.isVisible() && task1.getText().isBlank())
        {
        task1.setText(jTextField1.getText());
        task1.setVisible(true);
        }
        else if(!task2.isVisible() && task2.getText().isBlank())
        {
        task2.setText(jTextField1.getText());
        task2.setVisible(true);
        }
        else if(!task3.isVisible() && task3.getText().isBlank())
        {
        task3.setText(jTextField1.getText());
        task3.setVisible(true);
        }
        else if(!task4.isVisible() && task4.getText().isBlank())
        {
        task4.setText(jTextField1.getText());
        task4.setVisible(true);
        }
        else if(!task5.isVisible() && task5.getText().isBlank())
        {
        task5.setText(jTextField1.getText());
        task5.setVisible(true);
        }
        else if(!task6.isVisible() && task6.getText().isBlank())
        {
        task6.setText(jTextField1.getText());
        task6.setVisible(true);
        }
        else if(!task7.isVisible() && task7.getText().isBlank())
        {
        task7.setText(jTextField1.getText());
        task7.setVisible(true);
        }
        else if(!task8.isVisible() && task8.getText().isBlank())
        {
        task8.setText(jTextField1.getText());
        task8.setVisible(true);
        }
        else if(!task9.isVisible() && task9.getText().isBlank())
        {
        task9.setText(jTextField1.getText());
        task9.setVisible(true);
        }
        else if(!task10.isVisible() && task10.getText().isBlank())
        {
        task10.setText(jTextField1.getText());
        task10.setVisible(true);
        }
        else {
            maxTaskMessage.setVisible(true);
        }
        
        

    }//GEN-LAST:event_confirmButtonActionPerformed

    private void deleteTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskButtonActionPerformed
        // This button checks the combo box for the task selected to delete content and set the visibility to false, so it can be use again.
        if(jComboBox1.getSelectedItem()=="task1"){
        task1.setText("");
        task1.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
        
        if(jComboBox1.getSelectedItem()=="task2"){
        task2.setText("");
        task2.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
        
        if(jComboBox1.getSelectedItem()=="task3"){
        task3.setText("");
        task3.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
        
        if(jComboBox1.getSelectedItem()=="task4"){
        task4.setText("");
        task4.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
        
        if(jComboBox1.getSelectedItem()=="task5"){
        task5.setText("");
        task5.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
        
        if(jComboBox1.getSelectedItem()=="task6"){
        task6.setText("");
        task6.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
        
        if(jComboBox1.getSelectedItem()=="task7"){
        task7.setText("");
        task7.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
        
        if(jComboBox1.getSelectedItem()=="task8"){
        task8.setText("");
        task8.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
        
        if(jComboBox1.getSelectedItem()=="task9"){
        task9.setText("");
        task9.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
        
        if(jComboBox1.getSelectedItem()=="task10"){
        task10.setText("");
        task10.setVisible(false);
        maxTaskMessage.setVisible(false);
        }
    }//GEN-LAST:event_deleteTaskButtonActionPerformed

    private void deleteAllTasksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllTasksButtonActionPerformed
        // This button deletes all text from the task labels and set visibility false for a reset of the list of task
        
        task1.setText("");
        task1.setVisible(false);

        task2.setText("");
        task2.setVisible(false);

        task3.setText("");
        task3.setVisible(false);

        task4.setText("");
        task4.setVisible(false);

        task5.setText("");
        task5.setVisible(false);

        task6.setText("");
        task6.setVisible(false);

        task7.setText("");
        task7.setVisible(false);
 
        task8.setText("");
        task8.setVisible(false);
        
        task9.setText("");
        task9.setVisible(false);
 
        task10.setText("");
        task10.setVisible(false);        

        maxTaskMessage.setVisible(false);

    }//GEN-LAST:event_deleteAllTasksButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGrLbl;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton deleteAllTasksButton;
    private javax.swing.JButton deleteTaskButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel maxTaskMessage;
    private javax.swing.JLabel task1;
    private javax.swing.JLabel task10;
    private javax.swing.JLabel task2;
    private javax.swing.JLabel task3;
    private javax.swing.JLabel task4;
    private javax.swing.JLabel task5;
    private javax.swing.JLabel task6;
    private javax.swing.JLabel task7;
    private javax.swing.JLabel task8;
    private javax.swing.JLabel task9;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private PopupMenu toString(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
